---
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: co
  namespace: ibm-common-services 
spec:
  pvcSelector: {}
  replicationState: primary
  s3Profiles:
  - s3profile-cluster6-ocs-external-storagecluster
  - s3profile-cluster8-ocs-external-storagecluster
  sync:
    mode: Enabled
  volSync:
    disabled: true
  kubeObjectProtection:
    recipeRef:
      name: ibmcpd-operators
      captureWorkflowName: capture
      recoverWorkflowName: recover
      volumeGroupName: cpd-operators-volumes 
  action:
    Relocate
